name: intimepro_mobile
description: InTimePro employee mobile application
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  dio: ^5.8.0+1
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.39
  path_provider: ^2.1.5
  path: ^1.9.1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  firebase_messaging: ^16.0.2
  flutter_local_notifications: ^19.4.2
  google_sign_in: ^7.2.0
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  retrofit_generator: ^10.2.3
  drift_dev: ^2.28.1
  build_runner: ^2.7.1
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
  assets:
    - .env
